---
apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-secrets
type: Opaque
data:
  DB_USER: "TODO"
  DB_PASSWORD: "TODO"
---
# Some value come from this example: https://gist.github.com/guizmaii/795374b8058240780aa995ef0f5b2ba7
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-configs
data:
  DB_HOST: "127.0.0.1"
  DB_PORT: "6432"
  LISTEN_PORT: "5432"
  TCP_KEEPALIVE: "1"
  TCP_KEEPCNT: "5"
  TCP_KEEPIDLE: "300" # see: https://git.io/vi0Aj
  TCP_KEEPINTVL: "300"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudsql-configs
data:
  DB_INSTANCES: "TODO"
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: DaemonSet
metadata:
  name: pgbouncer-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      name: pgbouncer-daemonset
  template:
    metadata:
      labels:
        name: pgbouncer-daemonset
    spec:
      containers:
        - image: guizmaii/pgbouncer:v1.7.2                # PgBouncer
          name: pgbouncer
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: pgbouncer-configs
            - secretRef:
                name: pgbouncer-secrets
        - image: gcr.io/cloudsql-docker/gce-proxy:1.11    # Gcloud SQL Proxy
          name: cloudsql-proxy
          command:
            - /cloud_sql_proxy
            - --dir=/cloudsql
            - -instances=$(DB_INSTANCES)
            - -credential_file=/secrets/cloudsql/credentials.json
          ports:
            - containerPort: 6432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: cloudsql-configs
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir: {}
